CREATE TABLE sys_user (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '用户编号',
  username VARCHAR(64) NOT NULL COMMENT '登录用户名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
  real_name VARCHAR(64) NOT NULL COMMENT '真实姓名',
  phone VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  email VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_code (code, deleted),
  UNIQUE KEY uk_sys_user_username (username, deleted),
  UNIQUE KEY uk_sys_user_phone (phone, deleted),
  KEY idx_sys_user_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台用户表';

CREATE TABLE sys_role (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '角色编码',
  name VARCHAR(64) NOT NULL COMMENT '角色名称',
  role_type VARCHAR(32) NOT NULL DEFAULT 'BUSINESS' COMMENT '角色类型',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_role_code (code, deleted),
  KEY idx_sys_role_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色表';

CREATE TABLE sys_permission (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(128) NOT NULL COMMENT '权限编码',
  name VARCHAR(64) NOT NULL COMMENT '权限名称',
  module VARCHAR(64) NOT NULL COMMENT '模块',
  action VARCHAR(64) NOT NULL COMMENT '动作',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_permission_code (code, deleted),
  KEY idx_sys_permission_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='权限表';

CREATE TABLE sys_menu (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '菜单编码',
  parent_id BIGINT DEFAULT NULL COMMENT '父菜单ID',
  name VARCHAR(64) NOT NULL COMMENT '菜单名称',
  path VARCHAR(255) DEFAULT NULL COMMENT '前端路由',
  component VARCHAR(255) DEFAULT NULL COMMENT '前端组件',
  icon VARCHAR(64) DEFAULT NULL COMMENT '图标',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_menu_code (code, deleted),
  KEY idx_sys_menu_parent (parent_id),
  KEY idx_sys_menu_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜单表';

CREATE TABLE sys_user_role (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sur_user_role (user_id, role_id, deleted),
  KEY idx_sur_user (user_id),
  KEY idx_sur_role (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户角色关联表';

CREATE TABLE sys_role_permission (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  permission_id BIGINT NOT NULL COMMENT '权限ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_srp_role_permission (role_id, permission_id, deleted),
  KEY idx_srp_role (role_id),
  KEY idx_srp_permission (permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色权限关联表';

CREATE TABLE sys_role_menu (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  menu_id BIGINT NOT NULL COMMENT '菜单ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_srm_role_menu (role_id, menu_id, deleted),
  KEY idx_srm_role (role_id),
  KEY idx_srm_menu (menu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色菜单关联表';

CREATE TABLE mobile_user (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '小程序用户编号',
  nickname VARCHAR(64) DEFAULT NULL COMMENT '昵称',
  avatar_url VARCHAR(500) DEFAULT NULL COMMENT '头像',
  phone VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  user_type VARCHAR(32) NOT NULL DEFAULT 'PUBLIC' COMMENT '用户类型',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_mobile_user_code (code, deleted),
  UNIQUE KEY uk_mobile_user_phone (phone, deleted),
  KEY idx_mobile_user_type (user_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='小程序用户表';

CREATE TABLE mobile_user_bind (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  mobile_user_id BIGINT NOT NULL COMMENT '小程序用户ID',
  bind_type VARCHAR(32) NOT NULL COMMENT '绑定类型',
  tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
  tenant_contact_id BIGINT DEFAULT NULL COMMENT '租户联系人ID',
  sys_user_id BIGINT DEFAULT NULL COMMENT '后台用户ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_mub_active_bind (mobile_user_id, bind_type, tenant_id, sys_user_id, deleted),
  KEY idx_mub_mobile_user (mobile_user_id),
  KEY idx_mub_tenant (tenant_id),
  KEY idx_mub_sys_user (sys_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='小程序绑定关系表';

CREATE TABLE wechat_identity (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  mobile_user_id BIGINT NOT NULL COMMENT '小程序用户ID',
  app_id VARCHAR(64) NOT NULL COMMENT '小程序AppID',
  openid VARCHAR(128) NOT NULL COMMENT '微信openid',
  unionid VARCHAR(128) DEFAULT NULL COMMENT '微信unionid',
  session_key_hash VARCHAR(255) DEFAULT NULL COMMENT 'session_key哈希',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wechat_openid (app_id, openid, deleted),
  KEY idx_wechat_mobile_user (mobile_user_id),
  KEY idx_wechat_unionid (unionid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信身份绑定表';

CREATE TABLE building (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '楼宇编号',
  name VARCHAR(128) NOT NULL COMMENT '楼宇名称',
  address VARCHAR(255) DEFAULT NULL COMMENT '地址',
  total_floor INT NOT NULL DEFAULT 0 COMMENT '总楼层',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_building_code (code, deleted),
  UNIQUE KEY uk_building_name (name, deleted),
  KEY idx_building_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='楼宇表';

CREATE TABLE building_floor (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '楼层编号',
  building_id BIGINT NOT NULL COMMENT '楼宇ID',
  floor_no INT NOT NULL COMMENT '楼层号',
  name VARCHAR(64) NOT NULL COMMENT '楼层名称',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_floor_code (code, deleted),
  UNIQUE KEY uk_floor_building_no (building_id, floor_no, deleted),
  KEY idx_floor_building (building_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='楼层表';

CREATE TABLE building_room (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '房间编号',
  building_id BIGINT NOT NULL COMMENT '楼宇ID',
  floor_id BIGINT NOT NULL COMMENT '楼层ID',
  room_no VARCHAR(64) NOT NULL COMMENT '房号',
  area DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '面积',
  usage_type VARCHAR(32) NOT NULL DEFAULT 'OFFICE' COMMENT '用途',
  rent_status VARCHAR(32) NOT NULL DEFAULT 'VACANT' COMMENT '租赁状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_room_code (code, deleted),
  UNIQUE KEY uk_room_no (building_id, room_no, deleted),
  KEY idx_room_building (building_id),
  KEY idx_room_floor (floor_id),
  KEY idx_room_rent_status (rent_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房间表';

CREATE TABLE tenant (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '租户编号',
  name VARCHAR(128) NOT NULL COMMENT '租户名称',
  credit_code VARCHAR(64) DEFAULT NULL COMMENT '统一社会信用代码',
  contact_phone VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_code (code, deleted),
  UNIQUE KEY uk_tenant_credit_code (credit_code, deleted),
  KEY idx_tenant_name (name),
  KEY idx_tenant_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户表';

CREATE TABLE tenant_contact (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '联系人编号',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  name VARCHAR(64) NOT NULL COMMENT '联系人姓名',
  phone VARCHAR(32) NOT NULL COMMENT '手机号',
  role VARCHAR(64) DEFAULT NULL COMMENT '联系人角色',
  is_primary TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主联系人',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_contact_code (code, deleted),
  UNIQUE KEY uk_contact_tenant_phone (tenant_id, phone, deleted),
  KEY idx_contact_tenant (tenant_id),
  KEY idx_contact_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户联系人表';

CREATE TABLE contract (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '合同编号',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  room_id BIGINT NOT NULL COMMENT '房间ID',
  start_date DATE NOT NULL COMMENT '开始日期',
  end_date DATE NOT NULL COMMENT '结束日期',
  rent_amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '租金金额',
  deposit_amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '押金金额',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_code (code, deleted),
  KEY idx_contract_tenant (tenant_id),
  KEY idx_contract_room (room_id),
  KEY idx_contract_end_date (end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同表';

CREATE TABLE contract_attachment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  file_id BIGINT NOT NULL COMMENT '文件ID',
  attachment_type VARCHAR(32) NOT NULL DEFAULT 'CONTRACT' COMMENT '附件类型',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_file (contract_id, file_id, deleted),
  KEY idx_contract_attach_contract (contract_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同附件表';

CREATE TABLE bill (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '账单编号',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  contract_id BIGINT DEFAULT NULL COMMENT '合同ID',
  source_type VARCHAR(32) NOT NULL COMMENT '来源类型',
  source_id BIGINT DEFAULT NULL COMMENT '来源ID',
  bill_type VARCHAR(32) NOT NULL COMMENT '账单类型',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '应收金额',
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '已付金额',
  due_date DATE DEFAULT NULL COMMENT '到期日期',
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态',
  pay_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_bill_code (code, deleted),
  KEY idx_bill_tenant (tenant_id),
  KEY idx_bill_due_date (due_date),
  KEY idx_bill_pay_status (pay_status),
  KEY idx_bill_source (source_type, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='账单表';

CREATE TABLE bill_payment_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '支付流水编号',
  bill_id BIGINT NOT NULL COMMENT '账单ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  pay_channel VARCHAR(32) NOT NULL COMMENT '支付渠道',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '支付金额',
  transaction_no VARCHAR(128) DEFAULT NULL COMMENT '交易号',
  paid_at DATETIME DEFAULT NULL COMMENT '支付时间',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_code (code, deleted),
  UNIQUE KEY uk_payment_transaction (transaction_no, deleted),
  KEY idx_payment_bill (bill_id),
  KEY idx_payment_tenant (tenant_id),
  KEY idx_payment_paid_at (paid_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付记录表';

CREATE TABLE bill_invoice (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '开票编号',
  bill_id BIGINT NOT NULL COMMENT '账单ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  invoice_title VARCHAR(128) NOT NULL COMMENT '发票抬头',
  tax_no VARCHAR(64) DEFAULT NULL COMMENT '税号',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '开票金额',
  invoice_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '开票状态',
  issued_at DATETIME DEFAULT NULL COMMENT '开票时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoice_code (code, deleted),
  KEY idx_invoice_bill (bill_id),
  KEY idx_invoice_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='开票记录表';

CREATE TABLE bill_invoice_attachment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  invoice_id BIGINT NOT NULL COMMENT '发票ID',
  file_id BIGINT NOT NULL COMMENT '文件ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoice_file (invoice_id, file_id, deleted),
  KEY idx_invoice_attach_invoice (invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='发票附件表';

CREATE TABLE meeting_room (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '会议室编号',
  name VARCHAR(128) NOT NULL COMMENT '会议室名称',
  capacity INT NOT NULL DEFAULT 0 COMMENT '容纳人数',
  location VARCHAR(255) DEFAULT NULL COMMENT '位置',
  hourly_price DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '小时价格',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_meeting_room_code (code, deleted),
  KEY idx_meeting_room_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会议室表';

CREATE TABLE meeting_booking (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '预约编号',
  meeting_room_id BIGINT NOT NULL COMMENT '会议室ID',
  tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
  applicant_mobile_user_id BIGINT DEFAULT NULL COMMENT '申请小程序用户ID',
  start_time DATETIME NOT NULL COMMENT '开始时间',
  end_time DATETIME NOT NULL COMMENT '结束时间',
  booking_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '预约状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_meeting_booking_code (code, deleted),
  KEY idx_booking_room_time (meeting_room_id, start_time, end_time),
  KEY idx_booking_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会议预约表';

CREATE TABLE meeting_bill (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '会议账单编号',
  booking_id BIGINT NOT NULL COMMENT '会议预约ID',
  bill_id BIGINT DEFAULT NULL COMMENT '通用账单ID',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '金额',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_meeting_bill_code (code, deleted),
  UNIQUE KEY uk_meeting_bill_booking (booking_id, deleted),
  KEY idx_meeting_bill_booking (booking_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会议账单表';

CREATE TABLE parking_space (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '车位编号',
  space_no VARCHAR(64) NOT NULL COMMENT '车位号',
  location VARCHAR(128) DEFAULT NULL COMMENT '位置',
  space_type VARCHAR(32) NOT NULL DEFAULT 'STANDARD' COMMENT '车位类型',
  rent_status VARCHAR(32) NOT NULL DEFAULT 'VACANT' COMMENT '租赁状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_parking_space_code (code, deleted),
  UNIQUE KEY uk_parking_space_no (space_no, deleted),
  KEY idx_parking_status (rent_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='车位表';

CREATE TABLE parking_assignment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '车位绑定编号',
  parking_space_id BIGINT NOT NULL COMMENT '车位ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  car_plate_no VARCHAR(32) NOT NULL COMMENT '车牌号',
  start_date DATE NOT NULL COMMENT '开始日期',
  end_date DATE DEFAULT NULL COMMENT '结束日期',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_parking_assignment_code (code, deleted),
  UNIQUE KEY uk_parking_active_space (parking_space_id, status, deleted),
  KEY idx_parking_assign_tenant (tenant_id),
  KEY idx_parking_assign_car (car_plate_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='车位租赁绑定表';

CREATE TABLE parking_bill (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '停车账单编号',
  assignment_id BIGINT NOT NULL COMMENT '车位绑定ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '金额',
  due_date DATE DEFAULT NULL COMMENT '到期日期',
  pay_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_parking_bill_code (code, deleted),
  KEY idx_parking_bill_tenant (tenant_id),
  KEY idx_parking_bill_due (due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='停车账单表';

CREATE TABLE work_order (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '工单编号',
  tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
  room_id BIGINT DEFAULT NULL COMMENT '房间ID',
  submitter_mobile_user_id BIGINT DEFAULT NULL COMMENT '提交小程序用户ID',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  category VARCHAR(32) NOT NULL COMMENT '类别',
  priority VARCHAR(32) NOT NULL DEFAULT 'NORMAL' COMMENT '优先级',
  work_status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '工单状态',
  assignee_id BIGINT DEFAULT NULL COMMENT '处理人ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_workorder_code (code, deleted),
  KEY idx_workorder_tenant (tenant_id),
  KEY idx_workorder_status (work_status),
  KEY idx_workorder_assignee (assignee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单表';

CREATE TABLE work_order_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  work_order_id BIGINT NOT NULL COMMENT '工单ID',
  operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
  action VARCHAR(32) NOT NULL COMMENT '动作',
  content VARCHAR(1000) DEFAULT NULL COMMENT '处理内容',
  operated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  KEY idx_wor_order (work_order_id),
  KEY idx_wor_operator (operator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单处理记录表';

CREATE TABLE work_order_attachment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  work_order_id BIGINT NOT NULL COMMENT '工单ID',
  file_id BIGINT NOT NULL COMMENT '文件ID',
  attachment_type VARCHAR(32) NOT NULL DEFAULT 'IMAGE' COMMENT '附件类型',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wo_file (work_order_id, file_id, deleted),
  KEY idx_wo_attach_order (work_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单附件表';

CREATE TABLE visitor_appointment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '访客预约编号',
  tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
  visitor_name VARCHAR(64) NOT NULL COMMENT '访客姓名',
  visitor_phone VARCHAR(32) NOT NULL COMMENT '访客手机号',
  car_plate_no VARCHAR(32) DEFAULT NULL COMMENT '车牌号',
  visit_time DATETIME NOT NULL COMMENT '访问时间',
  appointment_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '预约状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_visitor_code (code, deleted),
  KEY idx_visitor_tenant (tenant_id),
  KEY idx_visitor_phone (visitor_phone),
  KEY idx_visitor_time (visit_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='访客预约表';

CREATE TABLE visitor_pass_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  appointment_id BIGINT NOT NULL COMMENT '预约ID',
  pass_type VARCHAR(32) NOT NULL COMMENT '通行类型',
  pass_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '通行时间',
  gate_name VARCHAR(64) DEFAULT NULL COMMENT '门岗名称',
  operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  KEY idx_pass_appointment (appointment_id),
  KEY idx_pass_time (pass_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='访客通行记录表';

CREATE TABLE investment_display (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '招商展示编号',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  content TEXT NOT NULL COMMENT '内容',
  cover_file_id BIGINT DEFAULT NULL COMMENT '封面文件ID',
  publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_invest_display_code (code, deleted),
  KEY idx_invest_display_publish (publish_status),
  KEY idx_invest_display_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='招商展示表';

CREATE TABLE investment_lead (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '招商线索编号',
  name VARCHAR(64) NOT NULL COMMENT '联系人',
  phone VARCHAR(32) NOT NULL COMMENT '手机号',
  company_name VARCHAR(128) DEFAULT NULL COMMENT '公司名称',
  desired_area DECIMAL(10,2) DEFAULT NULL COMMENT '意向面积',
  intended_use VARCHAR(255) DEFAULT NULL COMMENT '意向用途',
  source VARCHAR(32) NOT NULL DEFAULT 'MINIPROGRAM' COMMENT '来源',
  lead_status VARCHAR(32) NOT NULL DEFAULT 'NEW' COMMENT '线索状态',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_invest_lead_code (code, deleted),
  KEY idx_lead_phone (phone),
  KEY idx_lead_status (lead_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='招商线索表';

CREATE TABLE investment_follow_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  lead_id BIGINT NOT NULL COMMENT '线索ID',
  follower_id BIGINT DEFAULT NULL COMMENT '跟进人ID',
  follow_type VARCHAR(32) NOT NULL COMMENT '跟进类型',
  content VARCHAR(1000) DEFAULT NULL COMMENT '跟进内容',
  next_follow_at DATETIME DEFAULT NULL COMMENT '下次跟进时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  KEY idx_follow_lead (lead_id),
  KEY idx_follow_next (next_follow_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='招商跟进记录表';

CREATE TABLE staff_checkin (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '签到编号',
  sys_user_id BIGINT NOT NULL COMMENT '员工ID',
  checkin_type VARCHAR(32) NOT NULL COMMENT '签到类型',
  checkin_time DATETIME NOT NULL COMMENT '签到时间',
  location VARCHAR(255) DEFAULT NULL COMMENT '位置',
  longitude DECIMAL(10,6) DEFAULT NULL COMMENT '经度',
  latitude DECIMAL(10,6) DEFAULT NULL COMMENT '纬度',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_checkin_code (code, deleted),
  KEY idx_checkin_user_time (sys_user_id, checkin_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工签到表';

CREATE TABLE staff_checkin_stats (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  sys_user_id BIGINT NOT NULL COMMENT '员工ID',
  stats_date DATE NOT NULL COMMENT '统计日期',
  on_duty_count INT NOT NULL DEFAULT 0 COMMENT '上班签到次数',
  off_duty_count INT NOT NULL DEFAULT 0 COMMENT '下班签到次数',
  abnormal_count INT NOT NULL DEFAULT 0 COMMENT '异常次数',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_checkin_stats_user_date (sys_user_id, stats_date),
  KEY idx_checkin_stats_date (stats_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='签到统计表';

CREATE TABLE file_upload (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '文件编号',
  biz_type VARCHAR(64) DEFAULT NULL COMMENT '业务类型',
  biz_id BIGINT DEFAULT NULL COMMENT '业务ID',
  original_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
  stored_name VARCHAR(255) NOT NULL COMMENT '存储文件名',
  storage_path VARCHAR(500) NOT NULL COMMENT '存储路径',
  mime_type VARCHAR(128) DEFAULT NULL COMMENT '文件类型',
  file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_file_code (code, deleted),
  KEY idx_file_biz (biz_type, biz_id),
  KEY idx_file_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件上传记录表';

CREATE TABLE log_operation (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '日志编号',
  operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
  operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人',
  module VARCHAR(64) NOT NULL COMMENT '模块',
  action VARCHAR(64) NOT NULL COMMENT '动作',
  request_uri VARCHAR(255) DEFAULT NULL COMMENT '请求URI',
  request_method VARCHAR(16) DEFAULT NULL COMMENT '请求方法',
  client_ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
  result_status VARCHAR(32) NOT NULL COMMENT '结果状态',
  operated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_op_log_code (code),
  KEY idx_op_log_operator (operator_id),
  KEY idx_op_log_time (operated_at),
  KEY idx_op_log_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';

CREATE TABLE log_login (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '登录日志编号',
  user_type VARCHAR(32) NOT NULL COMMENT '用户类型',
  user_id BIGINT DEFAULT NULL COMMENT '用户ID',
  username VARCHAR(64) DEFAULT NULL COMMENT '用户名',
  client_ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
  login_result VARCHAR(32) NOT NULL COMMENT '登录结果',
  login_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_login_log_code (code),
  KEY idx_login_user (user_type, user_id),
  KEY idx_login_time (login_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='登录日志表';

CREATE TABLE notice (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(64) NOT NULL COMMENT '公告编号',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  content TEXT NOT NULL COMMENT '内容',
  notice_type VARCHAR(32) NOT NULL DEFAULT 'GENERAL' COMMENT '公告类型',
  publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态',
  published_at DATETIME DEFAULT NULL COMMENT '发布时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id),
  UNIQUE KEY uk_notice_code (code, deleted),
  KEY idx_notice_publish (publish_status, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公告表';

CREATE TABLE notice_read_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  notice_id BIGINT NOT NULL COMMENT '公告ID',
  reader_type VARCHAR(32) NOT NULL COMMENT '阅读人类型',
  reader_id BIGINT NOT NULL COMMENT '阅读人ID',
  read_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '阅读时间',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  updated_by BIGINT DEFAULT NULL COMMENT '更新人',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_notice_reader (notice_id, reader_type, reader_id, deleted),
  KEY idx_notice_read_notice (notice_id),
  KEY idx_notice_read_reader (reader_type, reader_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公告阅读记录表';
