package com.dehui.property.modules.workorder.dto;

import lombok.Data;
import com.dehui.property.modules.attachment.dto.AttachmentResponse;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Data
public class WorkOrderResponse {
    private Long id;
    private String orderNumber;
    private String title;
    private String description;
    private Long equipmentId;
    private String location;
    private String orderType;
    private String category;
    private String priority;
    private String status;
    private String statusLabel;
    private String orderTypeLabel;
    private String categoryLabel;
    private String priorityLabel;
    private String source;
    private String sourceLabel;
    private Boolean slaOverdue;
    private String slaLabel;
    private Long reporterId;
    private Long mobileUserId;
    private Long tenantId;
    private String tenantName;
    private String reporterName;
    private String reporterPhone;
    private List<String> imageUrls;
    private List<AttachmentResponse> reportAttachments;
    private List<AttachmentResponse> beforeAttachments;
    private List<AttachmentResponse> afterAttachments;
    private String handlingResult;
    private Boolean billable;
    private BigDecimal chargeAmount;
    private String chargeRemark;
    private Long billId;
    private Integer rating;
    private String evaluationContent;
    private LocalDateTime evaluationTime;
    private Long handlerId;
    private String handlerName;
    private Long inspectionRecordId;
    private String remark;
    private List<WorkOrderLogResponse> logs;
    private LocalDateTime submittedTime;
    private LocalDateTime assignedTime;
    private LocalDateTime processingTime;
    private LocalDateTime completedTime;
    private LocalDateTime closedTime;
    private LocalDateTime cancelledTime;
    private LocalDateTime confirmedTime;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;
}
